#!/bin/bash
#

Bootstrap: docker
From: phusion/baseimage:0.11

%label
	MAINTAINER Hugo Mananet
	VERSION 2.3.6


%post
	apt-get -y update
	apt-get -y install build-essential \
	wget \
	make \
	gcc \
	autoconf \
	perl \
	ca-certificates \
	curl \
	libbz2-dev \
	liblzma-dev \
	libncurses5-dev \
	libncursesw5-dev \
	zlib1g-dev \


	mkdir -p /opt/
	wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 && mv samtools-1.9.tar.bz2 /opt/
	wget https://github.com/samtools/bcftools/releases/download/1.9/bcftools-1.9.tar.bz2 && mv bcftools-1.9.tar.bz2 /opt/
	cd /opt/ && tar xjvf samtools-1.9.tar.bz2 && tar xjvf bcftools-1.9.tar.bz2

	cd /opt/samtools-1.9/ && ./configure && make
	cd /opt/ && rm samtools-1.9.tar.bz2

	cd /opt/bcftools-1.9/ && ./configure && make
	cd /opt/ && rm bcftools-1.9.tar.bz2

	ln -s /opt/samtools-1.9/samtools /bin
	ln -s /opt/bcftools-1.9/bcftools /bin
	ln -s /opt/samtools-1.9/misc/* /bin
	ln -s /opt/bcftools-1.9/misc/* /bin
