#!/bin/bash
#

Bootstrap: docker
From: phusion/baseimage:0.11

%label
	MAINTAINER Hugo Mananet
	VERSION 2.3.6


%post
	apt-get -y update
	apt-get -y install build-essential \
	wget \
	make \
	gcc \
	autoconf \
	perl \
	ca-certificates \
	curl \
	libbz2-dev \
	liblzma-dev \
	libncurses5-dev \
	libncursesw5-dev \
	zlib1g-dev \



	mkdir -p /opt/
	wget https://sourceforge.net/projects/samtools/files/samtools/0.1.18/samtools-0.1.18.tar.bz2 && mv samtools-0.1.18.tar.bz2 /opt/

	cd /opt/ && tar xjvf samtools-0.1.18.tar.bz2
	cd /opt/samtools-0.1.18/ && make
	cd /opt/ && rm samtools-0.1.18.tar.bz2
	cp /opt/samtools-0.1.18/samtools /opt/samtools-0.1.18/misc/
	cp /opt/samtools-0.1.18/bcftools/bcftools /opt/samtools-0.1.18/misc/
	cp /opt/samtools-0.1.18/bcftools/vcfutils.pl /opt/samtools-0.1.18/misc/
	ln -s /opt/samtools-0.1.18/misc/samtools /bin
	ln -s /opt/samtools-0.1.18/misc/bcftools /bin
	ln -s /opt/samtools-0.1.18/misc/wgsim /bin
	ln -s /opt/samtools-0.1.18/misc/seqtk /bin
	ln -s /opt/samtools-0.1.18/misc/maq2sam-long /bin
	ln -s /opt/samtools-0.1.18/misc/maq2sam-short /bin
	ln -s /opt/samtools-0.1.18/misc/*.pl /bin
	ln -s /opt/samtools-0.1.18/misc/*.py /bin


%environment
	export LANGUAGE=fr_FR.UTF-8
	export LANG=fr_FR.UTF-8
	export LC_ALL=fr_FR.UTF-8
