#!/bin/bash
#

Bootstrap: docker
From: phusion/baseimage:0.11

%label
	MAINTAINER Hugo Mananet
	VERSION 2.3.6


%post
	apt-get -y update
	apt-get -y install build-essential \
	wget \
	make \
	gcc \
	autoheader \
	autoconf \
	perl \
	ca-certificates \
	curl \
	libbz2-dev \
	liblzma-dev \
	libncurses5-dev \
	libncursesw5-dev \
	zlib1g-dev \



	mkdir -p /opt/samtools_0.1.18/
	wget https://sourceforge.net/projects/samtools/files/samtools/0.1.18/samtools-0.1.18.tar.bz2 && mv samtools-0.1.18.tar.bz2 /opt/samtools_0.1.18/

	cd /opt/samtools_0.1.18/ && tar xjvf samtools-0.1.18.tar.bz2
	cd /opt/samtools_0.1.18/ && ./configure && make && make install
	cd /opt/samtools_0.1.18/ && rm samtools-0.1.18.tar.bz2

%environment
	export LANGUAGE=fr_FR.UTF-8
	export LANG=fr_FR.UTF-8
	export LC_ALL=fr_FR.UTF-8
